# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'aendern.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Aendern(object):
    def setupUi(self, Aendern):
        Aendern.setObjectName("Aendern")
        Aendern.setWindowModality(QtCore.Qt.WindowModal)
        Aendern.resize(1302, 886)
        Aendern.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        icon = QtGui.QIcon.fromTheme("icon.ico")
        Aendern.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(Aendern)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pBar = QtWidgets.QProgressBar(Aendern)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(120)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.pBar.sizePolicy().hasHeightForWidth())
        self.pBar.setSizePolicy(sizePolicy)
        self.pBar.setProperty("value", 0)
        self.pBar.setObjectName("pBar")
        self.horizontalLayout_2.addWidget(self.pBar)
        spacerItem1 = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.Anzahl = QtWidgets.QLabel(Aendern)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.Anzahl.sizePolicy().hasHeightForWidth())
        self.Anzahl.setSizePolicy(sizePolicy)
        self.Anzahl.setText("")
        self.Anzahl.setObjectName("Anzahl")
        self.horizontalLayout_2.addWidget(self.Anzahl)
        self.gridLayout.addLayout(self.horizontalLayout_2, 11, 1, 1, 8)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Mark_lbl = QtWidgets.QLabel(Aendern)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.Mark_lbl.sizePolicy().hasHeightForWidth())
        self.Mark_lbl.setSizePolicy(sizePolicy)
        self.Mark_lbl.setObjectName("Mark_lbl")
        self.horizontalLayout.addWidget(self.Mark_lbl)
        self.replace_cBox = QtWidgets.QComboBox(Aendern)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.replace_cBox.sizePolicy().hasHeightForWidth())
        self.replace_cBox.setSizePolicy(sizePolicy)
        self.replace_cBox.setEditable(True)
        self.replace_cBox.setObjectName("replace_cBox")
        self.horizontalLayout.addWidget(self.replace_cBox)
        spacerItem3 = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.del_Btn = QtWidgets.QPushButton(Aendern)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.del_Btn.sizePolicy().hasHeightForWidth())
        self.del_Btn.setSizePolicy(sizePolicy)
        self.del_Btn.setObjectName("del_Btn")
        self.horizontalLayout.addWidget(self.del_Btn)
        self.replaceBtn = QtWidgets.QPushButton(Aendern)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.replaceBtn.sizePolicy().hasHeightForWidth())
        self.replaceBtn.setSizePolicy(sizePolicy)
        self.replaceBtn.setObjectName("replaceBtn")
        self.horizontalLayout.addWidget(self.replaceBtn)
        self.gridLayout.addLayout(self.horizontalLayout, 13, 1, 1, 8)
        self.Info_lbl = QtWidgets.QLabel(Aendern)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.Info_lbl.sizePolicy().hasHeightForWidth())
        self.Info_lbl.setSizePolicy(sizePolicy)
        self.Info_lbl.setText("")
        self.Info_lbl.setObjectName("Info_lbl")
        self.gridLayout.addWidget(self.Info_lbl, 8, 1, 1, 1)
        self.pasteBtn = QtWidgets.QPushButton(Aendern)
        self.pasteBtn.setObjectName("pasteBtn")
        self.gridLayout.addWidget(self.pasteBtn, 8, 6, 1, 1)
        self.label = QtWidgets.QLabel(Aendern)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("ok.jpg"))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 8, 2, 1, 1)
        self.Ordner = QtWidgets.QLabel(Aendern)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.Ordner.setFont(font)
        self.Ordner.setObjectName("Ordner")
        self.gridLayout.addWidget(self.Ordner, 0, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(10, -1, 0, -1)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.OrdnerBtn = QtWidgets.QPushButton(Aendern)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OrdnerBtn.sizePolicy().hasHeightForWidth())
        self.OrdnerBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.OrdnerBtn.setFont(font)
        self.OrdnerBtn.setObjectName("OrdnerBtn")
        self.verticalLayout_2.addWidget(self.OrdnerBtn)
        spacerItem4 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem4)
        self.addDB_Btn = QtWidgets.QPushButton(Aendern)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addDB_Btn.sizePolicy().hasHeightForWidth())
        self.addDB_Btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.addDB_Btn.setFont(font)
        self.addDB_Btn.setObjectName("addDB_Btn")
        self.verticalLayout_2.addWidget(self.addDB_Btn)
        spacerItem5 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem5)
        self.einfuegBtn = QtWidgets.QPushButton(Aendern)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.einfuegBtn.sizePolicy().hasHeightForWidth())
        self.einfuegBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.einfuegBtn.setFont(font)
        self.einfuegBtn.setObjectName("einfuegBtn")
        self.verticalLayout_2.addWidget(self.einfuegBtn)
        spacerItem6 = QtWidgets.QSpacerItem(40, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem6)
        self.ZurueckBtn = QtWidgets.QPushButton(Aendern)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ZurueckBtn.sizePolicy().hasHeightForWidth())
        self.ZurueckBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.ZurueckBtn.setFont(font)
        self.ZurueckBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ZurueckBtn.setObjectName("ZurueckBtn")
        self.verticalLayout_2.addWidget(self.ZurueckBtn)
        spacerItem7 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem7)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 9, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem8, 14, 8, 1, 1)
        self.copyBtn = QtWidgets.QPushButton(Aendern)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.copyBtn.sizePolicy().hasHeightForWidth())
        self.copyBtn.setSizePolicy(sizePolicy)
        self.copyBtn.setObjectName("copyBtn")
        self.gridLayout.addWidget(self.copyBtn, 8, 5, 1, 1)
        self.delBtn = QtWidgets.QPushButton(Aendern)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delBtn.sizePolicy().hasHeightForWidth())
        self.delBtn.setSizePolicy(sizePolicy)
        self.delBtn.setObjectName("delBtn")
        self.gridLayout.addWidget(self.delBtn, 8, 4, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem9, 1, 10, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(Aendern)
        self.tableWidget.setRowCount(16)
        self.tableWidget.setColumnCount(14)
        self.tableWidget.setObjectName("tableWidget")
        self.gridLayout.addWidget(self.tableWidget, 1, 1, 6, 8)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Muster = QtWidgets.QLabel(Aendern)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.Muster.sizePolicy().hasHeightForWidth())
        self.Muster.setSizePolicy(sizePolicy)
        self.Muster.setObjectName("Muster")
        self.horizontalLayout_3.addWidget(self.Muster)
        self.Muster_cBox = QtWidgets.QComboBox(Aendern)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.Muster_cBox.sizePolicy().hasHeightForWidth())
        self.Muster_cBox.setSizePolicy(sizePolicy)
        self.Muster_cBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Muster_cBox.setObjectName("Muster_cBox")
        self.horizontalLayout_3.addWidget(self.Muster_cBox)
        spacerItem10 = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem10)
        self.renamBtn = QtWidgets.QPushButton(Aendern)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.renamBtn.sizePolicy().hasHeightForWidth())
        self.renamBtn.setSizePolicy(sizePolicy)
        self.renamBtn.setObjectName("renamBtn")
        self.horizontalLayout_3.addWidget(self.renamBtn)
        self.gridLayout.addLayout(self.horizontalLayout_3, 12, 1, 1, 8)
        spacerItem11 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem11, 8, 3, 1, 1)

        self.retranslateUi(Aendern)
        self.ZurueckBtn.clicked.connect(self.ZurueckBtn.animateClick)
        QtCore.QMetaObject.connectSlotsByName(Aendern)
        Aendern.setTabOrder(self.OrdnerBtn, self.Muster_cBox)
        Aendern.setTabOrder(self.Muster_cBox, self.replaceBtn)

    def retranslateUi(self, Aendern):
        _translate = QtCore.QCoreApplication.translate
        Aendern.setWindowTitle(_translate("Aendern", "Form"))
        self.Mark_lbl.setText(_translate("Aendern", "2.markiere Stellen: "))
        self.del_Btn.setText(_translate("Aendern", "Löschen"))
        self.replaceBtn.setText(_translate("Aendern", "OK"))
        self.pasteBtn.setText(_translate("Aendern", "einfügen"))
        self.Ordner.setText(_translate("Aendern", "Ordner: "))
        self.OrdnerBtn.setToolTip(_translate("Aendern", "<html><head/><body><p>Er liest ein Ordner ein was neu ist, um die Dateinamen zu ändern</p></body></html>"))
        self.OrdnerBtn.setText(_translate("Aendern", "Ordner einlesen"))
        self.addDB_Btn.setText(_translate("Aendern", "Datenbank hinzufügen"))
        self.einfuegBtn.setText(_translate("Aendern", "  Daten einfügen  "))
        self.ZurueckBtn.setToolTip(_translate("Aendern", "<html><head/><body><p>Er liest ein Ordner ein was neu ist, um die Dateinamen zu ändern</p></body></html>"))
        self.ZurueckBtn.setText(_translate("Aendern", "       Zurück       "))
        self.copyBtn.setText(_translate("Aendern", "kopieren"))
        self.delBtn.setText(_translate("Aendern", "Löschen"))
        self.Muster.setText(_translate("Aendern", "1. Muster:"))
        self.renamBtn.setText(_translate("Aendern", "Ok"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Aendern = QtWidgets.QWidget()
    ui = Ui_Aendern()
    ui.setupUi(Aendern)
    Aendern.show()
    sys.exit(app.exec_())
