# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'suchen.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Suche(object):
    def setupUi(self, Suche):
        Suche.setObjectName("Suche")
        Suche.resize(832, 554)
        icon = QtGui.QIcon.fromTheme("xxx")
        Suche.setWindowIcon(icon)
        # Button 1 und 2
        self.Suchenbtn = QtWidgets.QPushButton(Suche)
        self.Suchenbtn.setGeometry(QtCore.QRect(500, 100, 191, 51))
        self.Zurueckbtn = QtWidgets.QPushButton(Suche)
        self.Zurueckbtn.setGeometry(QtCore.QRect(500, 190, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.Suchenbtn.setFont(font)
        self.Suchenbtn.setObjectName("Suchen")
        font = QtGui.QFont()
        font.setPointSize(24)
        self.Zurueckbtn.setFont(font)
        self.Zurueckbtn.setObjectName("Suchen_2")
        self.Zurueckbtn.clicked.connect(lambda:self.closeFenster(Suche))
        # Layout
        self.layoutWidget = QtWidgets.QWidget(Suche)
        self.layoutWidget.setGeometry(QtCore.QRect(240, 100, 121, 401))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkBox_17 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_17.setObjectName("checkBox_17")
        self.verticalLayout_3.addWidget(self.checkBox_17)
        self.checkBox_18 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_18.setObjectName("checkBox_18")
        self.verticalLayout_3.addWidget(self.checkBox_18)
        self.checkBox_19 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_19.setObjectName("checkBox_19")
        self.verticalLayout_3.addWidget(self.checkBox_19)
        self.checkBox_20 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_20.setObjectName("checkBox_20")
        self.verticalLayout_3.addWidget(self.checkBox_20)
        self.checkBox_21 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_21.setObjectName("checkBox_21")
        self.verticalLayout_3.addWidget(self.checkBox_21)
        self.checkBox_22 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_22.setObjectName("checkBox_22")
        self.verticalLayout_3.addWidget(self.checkBox_22)
        self.checkBox_23 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_23.setObjectName("checkBox_23")
        self.verticalLayout_3.addWidget(self.checkBox_23)
        self.checkBox_24 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_24.setObjectName("checkBox_24")
        self.verticalLayout_3.addWidget(self.checkBox_24)
        self.checkBox_25 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_25.setObjectName("checkBox_25")
        self.verticalLayout_3.addWidget(self.checkBox_25)
        self.checkBox_26 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_26.setObjectName("checkBox_26")
        self.verticalLayout_3.addWidget(self.checkBox_26)
        self.checkBox_27 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_27.setObjectName("checkBox_27")
        self.verticalLayout_3.addWidget(self.checkBox_27)
        self.checkBox_28 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_28.setObjectName("checkBox_28")
        self.verticalLayout_3.addWidget(self.checkBox_28)
        self.checkBox_29 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_29.setObjectName("checkBox_29")
        self.verticalLayout_3.addWidget(self.checkBox_29)
        self.checkBox_30 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_30.setObjectName("checkBox_30")
        self.verticalLayout_3.addWidget(self.checkBox_30)
        self.checkBox_31 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_31.setObjectName("checkBox_31")
        self.verticalLayout_3.addWidget(self.checkBox_31)
        self.checkBox_32 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_32.setObjectName("checkBox_32")
        self.verticalLayout_3.addWidget(self.checkBox_32)
        self.label = QtWidgets.QLabel(Suche)
        self.label.setGeometry(QtCore.QRect(80, 60, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Suche)
        self.label_2.setGeometry(QtCore.QRect(280, 60, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Suche)
        self.pushButton.setGeometry(QtCore.QRect(80, 30, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Suche)
        self.pushButton_2.setGeometry(QtCore.QRect(270, 30, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.widget = QtWidgets.QWidget(Suche)
        self.widget.setGeometry(QtCore.QRect(60, 100, 121, 401))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_13 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_13.setObjectName("checkBox_13")
        self.verticalLayout_2.addWidget(self.checkBox_13)
        self.checkBox_11 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_11.setObjectName("checkBox_11")
        self.verticalLayout_2.addWidget(self.checkBox_11)
        self.checkBox = QtWidgets.QCheckBox(self.widget)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_2.addWidget(self.checkBox)
        self.checkBox_14 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_14.setObjectName("checkBox_14")
        self.verticalLayout_2.addWidget(self.checkBox_14)
        self.checkBox_2 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_2.addWidget(self.checkBox_2)
        self.checkBox_10 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_10.setObjectName("checkBox_10")
        self.verticalLayout_2.addWidget(self.checkBox_10)
        self.checkBox_3 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_2.addWidget(self.checkBox_3)
        self.checkBox_9 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_9.setObjectName("checkBox_9")
        self.verticalLayout_2.addWidget(self.checkBox_9)
        self.checkBox_4 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout_2.addWidget(self.checkBox_4)
        self.checkBox_7 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_7.setObjectName("checkBox_7")
        self.verticalLayout_2.addWidget(self.checkBox_7)
        self.checkBox_5 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_5.setObjectName("checkBox_5")
        self.verticalLayout_2.addWidget(self.checkBox_5)
        self.checkBox_8 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_8.setObjectName("checkBox_8")
        self.verticalLayout_2.addWidget(self.checkBox_8)
        self.checkBox_6 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_6.setObjectName("checkBox_6")
        self.verticalLayout_2.addWidget(self.checkBox_6)
        self.checkBox_12 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_12.setObjectName("checkBox_12")
        self.verticalLayout_2.addWidget(self.checkBox_12)
        self.checkBox_15 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_15.setObjectName("checkBox_15")
        self.verticalLayout_2.addWidget(self.checkBox_15)
        self.checkBox_16 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_16.setObjectName("checkBox_16")
        self.verticalLayout_2.addWidget(self.checkBox_16)
        self.widget1 = QtWidgets.QWidget(Suche)
        self.widget1.setGeometry(QtCore.QRect(410, 270, 391, 41))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.was = QtWidgets.QLabel(self.widget1)
        self.was.setObjectName("was")
        self.horizontalLayout.addWidget(self.was)
        self.lineEdit = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)

        self.retranslateUi(Suche)
        QtCore.QMetaObject.connectSlotsByName(Suche)

    def retranslateUi(self, Suche):
        _translate = QtCore.QCoreApplication.translate
        Suche.setWindowTitle(_translate("Suche", "Form"))
        self.Suchenbtn.setText(_translate("Suche", "Suchen"))
        self.Zurueckbtn.setText(_translate("Suche", "Zurück"))
        self.checkBox_17.setText(_translate("Suche", "CheckBox"))
        self.checkBox_18.setText(_translate("Suche", "CheckBox"))
        self.checkBox_19.setText(_translate("Suche", "CheckBox"))
        self.checkBox_20.setText(_translate("Suche", "CheckBox"))
        self.checkBox_21.setText(_translate("Suche", "CheckBox"))
        self.checkBox_22.setText(_translate("Suche", "CheckBox"))
        self.checkBox_23.setText(_translate("Suche", "CheckBox"))
        self.checkBox_24.setText(_translate("Suche", "CheckBox"))
        self.checkBox_25.setText(_translate("Suche", "CheckBox"))
        self.checkBox_26.setText(_translate("Suche", "CheckBox"))
        self.checkBox_27.setText(_translate("Suche", "CheckBox"))
        self.checkBox_28.setText(_translate("Suche", "CheckBox"))
        self.checkBox_29.setText(_translate("Suche", "CheckBox"))
        self.checkBox_30.setText(_translate("Suche", "CheckBox"))
        self.checkBox_31.setText(_translate("Suche", "CheckBox"))
        self.checkBox_32.setText(_translate("Suche", "CheckBox"))
        self.label.setText(_translate("Suche", "Auswahl"))
        self.label_2.setText(_translate("Suche", "Wo ?"))        
        self.pushButton.setText(_translate("Suche", "Abwahl"))
        self.pushButton_2.setText(_translate("Suche", "Abwahl"))
        self.checkBox_13.setText(_translate("Suche", "CheckBox"))
        self.checkBox_11.setText(_translate("Suche", "CheckBox"))
        self.checkBox.setText(_translate("Suche", "CheckBox"))
        self.checkBox_14.setText(_translate("Suche", "CheckBox"))
        self.checkBox_2.setText(_translate("Suche", "CheckBox"))
        self.checkBox_10.setText(_translate("Suche", "CheckBox"))
        self.checkBox_3.setText(_translate("Suche", "CheckBox"))
        self.checkBox_9.setText(_translate("Suche", "CheckBox"))
        self.checkBox_4.setText(_translate("Suche", "CheckBox"))
        self.checkBox_7.setText(_translate("Suche", "CheckBox"))
        self.checkBox_5.setText(_translate("Suche", "CheckBox"))
        self.checkBox_8.setText(_translate("Suche", "CheckBox"))
        self.checkBox_6.setText(_translate("Suche", "CheckBox"))
        self.checkBox_12.setText(_translate("Suche", "CheckBox"))
        self.checkBox_15.setText(_translate("Suche", "CheckBox"))
        self.checkBox_16.setText(_translate("Suche", "CheckBox"))
        self.was.setText(_translate("Suche", "  Was?  "))

    def closeFenster(self,Suche):
        # hide the Screen on Exit
        Suche.hide()
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Suche = QtWidgets.QWidget()
    ui = Ui_Suche()
    ui.setupUi(Suche)
    Suche.show()
    sys.exit(app.exec_())
